apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server-app
  template:
    metadata:
      labels:
        app: server-app
    spec:
      containers:
        - name: server-container
          image: redis:latest
          ports:
            - containerPort: 6379
