apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - deployment.yaml
  - service.yaml

secretGenerator:
  - name: my-secret
    literals:
      - username=admin
      - password=secret
    type: Opaque
